/** The mdi paths the cards use, bundled at build time (no runtime dependency). */

import {
  mdiAirFilter,
  mdiAlertCircle,
  mdiAlertOutline,
  mdiArrowExpandVertical,
  mdiAutorenew,
  mdiBroom,
  mdiCarrot,
  mdiCheckCircle,
  mdiChefHat,
  mdiChevronDown,
  mdiClockOutline,
  mdiCounter,
  mdiCupWater,
  mdiCupcake,
  mdiDishwasher,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiDotsHorizontal,
  mdiFan,
  mdiFire,
  mdiFish,
  mdiFlash,
  mdiFlipHorizontal,
  mdiFoodDrumstick,
  mdiFoodSteak,
  mdiFoodVariant,
  mdiFrenchFries,
  mdiGlassWine,
  mdiGrill,
  mdiHeatWave,
  mdiInformationOutline,
  mdiLeaf,
  mdiLightningBolt,
  mdiPause,
  mdiPlay,
  mdiPotMix,
  mdiPotSteam,
  mdiPower,
  mdiRemote,
  mdiShakerOutline,
  mdiShimmer,
  mdiSnowflakeMelt,
  mdiSprayBottle,
  mdiStarOutline,
  mdiStop,
  mdiThermometer,
  mdiThermometerProbe,
  mdiTimerSand,
  mdiToasterOven,
  mdiTrayArrowDown,
  mdiTuneVariant,
  mdiVolumeOff,
  mdiWater,
  mdiWaterPercent,
  mdiWifi,
  mdiWifiOff,
  mdiWrenchOutline,
} from '@mdi/js';

export const ICONS = {
  // shared
  alert: mdiAlertOutline,
  check: mdiCheckCircle,
  chevron: mdiChevronDown,
  clock: mdiClockOutline,
  counter: mdiCounter,
  dots: mdiDotsHorizontal,
  error: mdiAlertCircle,
  info: mdiInformationOutline,
  pause: mdiPause,
  play: mdiPlay,
  power: mdiPower,
  remote: mdiRemote,
  stop: mdiStop,
  timer: mdiTimerSand,
  water: mdiWater,
  wifi: mdiWifi,
  wifi_off: mdiWifiOff,

  // dishwasher
  auto: mdiAutorenew,
  care: mdiWrenchOutline,
  dishwasher: mdiDishwasher,
  door: mdiDoorOpen,
  door_closed: mdiDoorClosed,
  dry: mdiAirFilter,
  energy: mdiLightningBolt,
  glass: mdiGlassWine,
  leaf: mdiLeaf,
  quick: mdiFlash,
  rack: mdiArrowExpandVertical,
  rinse: mdiCupWater,
  sanitize: mdiShimmer,
  silent: mdiVolumeOff,
  spray: mdiSprayBottle,
  water_percent: mdiWaterPercent,
  zone: mdiWaterPercent,

  // airfryer
  bake: mdiCupcake,
  chicken: mdiFoodDrumstick,
  clean: mdiBroom,
  defrost: mdiSnowflakeMelt,
  drawer: mdiTrayArrowDown,
  fan: mdiFan,
  fish: mdiFish,
  flip: mdiFlipHorizontal,
  fries: mdiFrenchFries,
  fryer: mdiToasterOven,
  heat: mdiFire,
  manual: mdiTuneVariant,
  meat: mdiFoodSteak,
  probe: mdiThermometerProbe,
  recipe: mdiChefHat,
  reheat: mdiHeatWave,
  roast: mdiGrill,
  shake: mdiShakerOutline,
  slow: mdiPotMix,
  snack: mdiFoodVariant,
  star: mdiStarOutline,
  steam: mdiPotSteam,
  temperature: mdiThermometer,
  vegetable: mdiCarrot,
  warm: mdiHeatWave,
};

export function icon(name, className = 'icon') {
  const path = ICONS[name] || ICONS.info;
  return `<svg class="${className}" viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"></path></svg>`;
}
