/** The mdi paths the cards use, bundled at build time (no runtime dependency). */

import {
  mdiAirFilter,
  mdiAlertCircle,
  mdiAlertOutline,
  mdiArrowExpandVertical,
  mdiAutorenew,
  mdiBellRingOutline,
  mdiBrightness6,
  mdiBroom,
  mdiCarrot,
  mdiCheckCircle,
  mdiChefHat,
  mdiChevronDown,
  mdiClockOutline,
  mdiCounter,
  mdiCupWater,
  mdiCupcake,
  mdiDishwasher,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiDotsHorizontal,
  mdiFan,
  mdiFire,
  mdiFish,
  mdiFlash,
  mdiFlipHorizontal,
  mdiFoodDrumstick,
  mdiFoodSteak,
  mdiFoodVariant,
  mdiFrenchFries,
  mdiGestureTap,
  mdiGlassWine,
  mdiGrill,
  mdiHeatWave,
  mdiInformationOutline,
  mdiLeaf,
  mdiLightningBolt,
  mdiPause,
  mdiPlay,
  mdiPotMix,
  mdiProjector,
  mdiPotSteam,
  mdiPower,
  mdiRemote,
  mdiShakerOutline,
  mdiShimmer,
  mdiSnowflakeMelt,
  mdiSprayBottle,
  mdiStarOutline,
  mdiStop,
  mdiThermometer,
  mdiThermometerProbe,
  mdiTimerSand,
  mdiToasterOven,
  mdiTrayArrowDown,
  mdiTuneVariant,
  mdiVolumeOff,
  mdiWater,
  mdiWaterPercent,
  mdiWifi,
  mdiWifiOff,
  mdiWrenchOutline,
  mdiAirConditioner,
  mdiCarBack,
  mdiCarBattery,
  mdiCarBrakeParking,
  mdiCarClock,
  mdiCarConnected,
  mdiCarConvertible,
  mdiCarCog,
  mdiCarDoor,
  mdiCarEstate,
  mdiCarLightHigh,
  mdiCarSpeedLimiter,
  mdiEvStation,
  mdiGasStation,
  mdiGauge,
  mdiHistory,
  mdiLock,
  mdiLockOpenVariant,
  mdiMapMarker,
  mdiOilLevel,
  mdiRoadVariant,
  mdiSnowflake,
  mdiSpeedometer,
  mdiSteering,
  mdiTimerOutline,
  mdiUpdate,
  mdiWindowClosedVariant,
  mdiWindowOpenVariant,
  mdiWrenchClock,
} from '@mdi/js';

export const ICONS = {
  // shared
  alert: mdiAlertOutline,
  check: mdiCheckCircle,
  chevron: mdiChevronDown,
  clock: mdiClockOutline,
  counter: mdiCounter,
  dots: mdiDotsHorizontal,
  error: mdiAlertCircle,
  info: mdiInformationOutline,
  pause: mdiPause,
  play: mdiPlay,
  power: mdiPower,
  remote: mdiRemote,
  stop: mdiStop,
  timer: mdiTimerSand,
  water: mdiWater,
  wifi: mdiWifi,
  wifi_off: mdiWifiOff,

  // dishwasher
  auto: mdiAutorenew,
  care: mdiWrenchOutline,
  brightness: mdiBrightness6,
  dishwasher: mdiDishwasher,
  door: mdiDoorOpen,
  door_closed: mdiDoorClosed,
  dry: mdiAirFilter,
  end_sound: mdiBellRingOutline,
  energy: mdiLightningBolt,
  floor_light: mdiProjector,
  glass: mdiGlassWine,
  leaf: mdiLeaf,
  key_tone: mdiGestureTap,
  quick: mdiFlash,
  rack: mdiArrowExpandVertical,
  rinse: mdiCupWater,
  sanitize: mdiShimmer,
  silent: mdiVolumeOff,
  spray: mdiSprayBottle,
  water_percent: mdiWaterPercent,
  zone: mdiWaterPercent,

  // airfryer
  bake: mdiCupcake,
  chicken: mdiFoodDrumstick,
  clean: mdiBroom,
  defrost: mdiSnowflakeMelt,
  drawer: mdiTrayArrowDown,
  fan: mdiFan,
  fish: mdiFish,
  flip: mdiFlipHorizontal,
  fries: mdiFrenchFries,
  fryer: mdiToasterOven,
  heat: mdiFire,
  manual: mdiTuneVariant,
  meat: mdiFoodSteak,
  probe: mdiThermometerProbe,
  recipe: mdiChefHat,
  reheat: mdiHeatWave,
  roast: mdiGrill,
  shake: mdiShakerOutline,
  slow: mdiPotMix,
  snack: mdiFoodVariant,
  star: mdiStarOutline,
  steam: mdiPotSteam,
  temperature: mdiThermometer,
  vegetable: mdiCarrot,
  warm: mdiHeatWave,

  // car
  ac: mdiAirConditioner,
  adblue: mdiOilLevel,
  battery_car: mdiCarBattery,
  bonnet: mdiCarCog,
  car: mdiCarEstate,
  car_door: mdiCarDoor,
  charger: mdiEvStation,
  fuel: mdiGasStation,
  gauge: mdiGauge,
  history: mdiHistory,
  lights: mdiCarLightHigh,
  lock: mdiLock,
  lock_open: mdiLockOpenVariant,
  marker: mdiMapMarker,
  motion: mdiCarSpeedLimiter,
  odometer: mdiSpeedometer,
  online: mdiCarConnected,
  parking: mdiCarBrakeParking,
  range: mdiRoadVariant,
  service: mdiWrenchClock,
  snowflake: mdiSnowflake,
  software: mdiUpdate,
  steering: mdiSteering,
  travel_time: mdiTimerOutline,
  trip: mdiCarClock,
  trunk: mdiCarBack,
  sunroof: mdiCarConvertible,
  window_closed: mdiWindowClosedVariant,
  window_open: mdiWindowOpenVariant,
};


export function icon(name, className = 'icon') {
  const path = ICONS[name] || ICONS.info;
  return `<svg class="${className}" viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"></path></svg>`;
}
