/** The mdi paths the card uses, bundled at build time (no runtime dependency). */

import {
  mdiAirFilter,
  mdiAlertCircle,
  mdiAlertOutline,
  mdiArrowExpandVertical,
  mdiAutorenew,
  mdiCheckCircle,
  mdiChevronDown,
  mdiClockOutline,
  mdiCounter,
  mdiCupWater,
  mdiDishwasher,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiFlash,
  mdiGlassWine,
  mdiLeaf,
  mdiLightningBolt,
  mdiPause,
  mdiPlay,
  mdiPower,
  mdiRemote,
  mdiShimmer,
  mdiSprayBottle,
  mdiStop,
  mdiTimerSand,
  mdiVolumeOff,
  mdiWater,
  mdiWaterPercent,
  mdiWifi,
  mdiWifiOff,
  mdiWrenchOutline,
} from '@mdi/js';

export const ICONS = {
  alert: mdiAlertOutline,
  error: mdiAlertCircle,
  auto: mdiAutorenew,
  care: mdiWrenchOutline,
  check: mdiCheckCircle,
  chevron: mdiChevronDown,
  clock: mdiClockOutline,
  counter: mdiCounter,
  dishwasher: mdiDishwasher,
  door: mdiDoorOpen,
  door_closed: mdiDoorClosed,
  dry: mdiAirFilter,
  energy: mdiLightningBolt,
  glass: mdiGlassWine,
  leaf: mdiLeaf,
  pause: mdiPause,
  play: mdiPlay,
  power: mdiPower,
  quick: mdiFlash,
  rack: mdiArrowExpandVertical,
  remote: mdiRemote,
  rinse: mdiCupWater,
  sanitize: mdiShimmer,
  silent: mdiVolumeOff,
  spray: mdiSprayBottle,
  stop: mdiStop,
  timer: mdiTimerSand,
  water: mdiWater,
  water_percent: mdiWaterPercent,
  wifi: mdiWifi,
  wifi_off: mdiWifiOff,
  zone: mdiWaterPercent,
};

export function icon(name, className = 'icon') {
  const path = ICONS[name] || ICONS.dishwasher;
  return `<svg class="${className}" viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"></path></svg>`;
}
